{% set name = "cbor2" %}
{% set version = "5.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cbor2-{{ version }}.tar.gz
  sha256: 43ce11e8c2fe4971d386d1a60cf83bfa0a4a667b97668ba76acbf5e6398821aa

build:
  skip: true  # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=40.7.0
    - setuptools-scm >=1.7.0
    - pip
  run:
    - python

test:
  imports:
    - cbor2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/agronholm/cbor2
  doc_url: https://cbor2.readthedocs.io/
  summary: CBOR (de)serializer with extensive tag support
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
